crm_python/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from leads.views import *
from django.contrib.auth.views import LoginView,  LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing-page"),
    path('leads/', include('leads.urls', namespace='leads')),
    path('login/', LoginView.as_view(), name="login"),
    path('signup/', SignupView.as_view(), name="signup"),
    path('logout/', LogoutView.as_view(), name="logout")

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import *

app_name = "leads"
urlpatterns = [
    path('', LeadListView.as_view(), name="lead_list"),
    path('details/<int:pk>', LeadDetailView.as_view(), name="details"),
    path('create', LeadCreateView.as_view(), name="create"),
    path('update/<int:pk>', LeadUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/', LeadDeleteView.as_view(), name="delete"),

]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    pass
#   after creating User with that method we should add AUTH_USER_MODEL = 'leads.User'

# we need to heritage from  AbstractUser to create our own users
# add the user to the settings

class Lead(models.Model):
    # SOURCE_CHOICES = (
    #     ('Youtube', 'Youtube'),
    #     ('Google', 'Google'),
    #     ('Newsletter', 'Newsletter')
    # )
    first_name = models.CharField(max_length=25,null=False )
    last_name = models.CharField(max_length=25, null=False)
    age = models.IntegerField(default=0)
    # phoned = models.BooleanField(default=False)
    # source = models.CharField(choices=SOURCE_CHOICES , max_length=220)
    # profile_picture = models.ImageField(blank=True ,  null=True)
    # special_file = models.FileField(blank=True ,  null=True)
    agent = models.ForeignKey("Agent", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id) + " " + self.first_name



# in the foreign key we put agent enter "" to say that Agent is in that file model

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username

leads/forms.py
from django import forms
from .views import *
from django.contrib.auth.forms import UserCreationForm ,  UsernameField
from  .models  import Lead
from django.contrib.auth import get_user_model

User = get_user_model()



class CustomerCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}


class LeadModelForms(forms.ModelForm):
    class Meta:
        model = Lead
        fields = '__all__'


class LeadFrom(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)

leads/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from .models import *
from .forms import *
from django.core.mail import send_mail
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView


# Create your views here.

class SignupView(CreateView):
    template_name = "registration/signup.html"
    form_class = CustomerCreationForm

    def get_success_url(self):
        return reverse("login")


class LandingPageView(TemplateView):
    template_name = "leads/landing.html"


class LeadListView(ListView):
    template_name = "leads/list_leads.html"
    queryset = Lead.objects.all()
    context_object_name = "leads"


class LeadDetailView(DetailView):
    template_name = "leads/leads_details.html"
    queryset = Lead.objects.all()
    context_object_name = "lead"


class LeadCreateView(CreateView):
    template_name = "leads/leads_create.html"
    form_class = LeadModelForms

    def get_success_url(self):
        return reverse("leads:lead_list")

    def form_valid(self, form):
        # todo send email
        send_mail(subject="A new lead has been made",
                  message="go to the site to see the new lead",
                  from_email="test@test.com",
                  recipient_list=["test2@hello.com"]
                  )
        return super(LeadCreateView, self).form_valid(form)


class LeadUpdateView(UpdateView):
    template_name = "leads/lead_update.html"
    queryset = Lead.objects.all()
    form_class = LeadModelForms

    def get_success_url(self):
        return reverse("leads:lead_list")


class LeadDeleteView(DeleteView):
    template_name = "leads/lead_delete.html"
    queryset = Lead.objects.all()

    def get_success_url(self):
        return reverse("leads:lead_list")


'''
def lead_delete(request, pk):
    lead = Lead.objects.get(pk=pk)
    lead.delete()
    return redirect("/leads")
def landing_page(request):
    return render(request, 'leads/landing.html')

def leads_list(request):
    leads = Lead.objects.all()
    context = {"leads": leads}
    return render(request, "leads/list_leads.html", context)
    # return HttpResponse('hello')

def leads_details(request, pk):
    lead = Lead.objects.get(id=pk)
    print(lead)
    context = {"lead": lead}
    return render(request, "leads/leads_details.html", context)

def leads_create(request):
    form = LeadModelForms()
    if request.method == "POST":
        form = LeadModelForms(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/leads')
    context = {
        "form": LeadModelForms()
    }
    return render(request, "leads/leads_create.html", context)

def lead_update(request, pk):
    lead = Lead.objects.get(pk=pk)
    form = LeadModelForms(instance=lead)
    if request.method == "POST":
        form = LeadModelForms(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect("/leads")
    context = {
        "form": form,
        "lead": lead
    }
    return render(request, 'leads/lead_update.html', context)
    '''

leads/templates/layouts/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
     <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <style>

    </style>
</head>
<body>

    <div class="max-w-6xl mx-auto  bg-gray-100">
        {% include 'layouts/navbar.html' %}
     {% block content %}
    {% endblock %}

        </div>
</body>
</html>

leads/templates/layouts/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">DJ CRM</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <a  href ="{% url 'leads:lead_list' %}" class="mr-5 hover:text-gray-1000">leads list</a>
      {% if not request.user.is_authenticated %}
          <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-1000">Signup</a>
      {% endif %}
    </nav>

      {% if request.user.is_authenticated %}

      Logged in as : {{ request.user.username }}
    <a href="{% url 'logout' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0 ml-3">Logout
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% else %}
    <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% endif %}


  </div>
</header>

leads/templates/leads/landing.html
{% extends 'layouts/base.html' %}

{% block content %}

  <section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">CRM built with django</h1>
        <p class="mb-8 leading-relaxed">
          This CRM helps you manage your leads
        </p>
        <div class="flex justify-center">
          <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
          <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

leads/templates/leads/lead_delete.html
{% extends 'layouts/base.html' %}

{% block title %}update lead{% endblock %}
{% block content %}

            <h1> Are you sure you wanna delete this  </h1>
            <form method= "post" >
                {% csrf_token %}
                {{ form.as_p }}
                <input  type="submit" value="submit"/>
            </form>
      </div>
    </div>
  </div>
</section>








<!-- form is an intentiated form object  base on the class models assosiated -->

{% endblock %}

leads/templates/leads/lead_update.html
{% extends 'layouts/base.html' %}

{% block title %}update lead{% endblock %}
{% block content %}


<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.firstname}}  {{lead.lastname}}</h1>
        <div class="flex mb-4">
          <a  href="{% url 'leads:details' pk=lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 ">Description</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
          <a href="{% url 'leads:update' pk=lead.id %}" class="  flex-grow text-red-500 border-b-2 border-red-500 py-2 text-lg px-1">Details</a>
        </div>
         <a href="{% url 'leads:lead_list' %}">Go back</a>
            <h1> Update a Lead </h1>
            <form method= "post" >
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="submit"/>
            </form>
          <a  href="{% url 'leads:delete' pk=lead.id %}" class="flex w-1/4 ml-auto text-white bg-red-400 border-0 py-2 px-6 focus:outline-none hover:bg-red-700 rounded">Delete</a>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>








<!-- form is an intentiated form object  base on the class models assosiated -->

{% endblock %}

leads/templates/leads/leads_create.html
{% extends 'layouts/base.html' %}

{% block title %}create lead{% endblock %}
{% block content %}
<a href="{% url 'leads:lead_list' %}">Go back</a>
<h1> Create a new Lead </h1>
<form method= "post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit"/>
</form>
<!-- form is an intentiated form object  base on the class models assosiated -->
{% endblock %}

leads/templates/leads/leads_details.html
{% extends 'layouts/base.html' %}


{% block title %}lead details{% endblock %}


{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.firstname}}  {{lead.lastname}}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
          <a href="{% url 'leads:update' pk=lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
        </div>
        <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{lead.age}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">location</span>
          <span class="ml-auto text-gray-900">dommie location</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Quantity</span>
          <span class="ml-auto text-gray-900">4</span>
        </div>
        <div class="flex">
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
          <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>





<!--    <a href="{% url 'leads:lead_list' %}">Go back</a>-->
<!--    <button href="{% url 'leads:create' %}"> Create a New form </button>-->

{% endblock%}

leads/templates/leads/list_leads.html
{% extends 'layouts/base.html' %}

{% block title %}
list leads
{% endblock %}
    {% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <div class="w-full  py-6 md-6 flex justify-between items-center border-b border-gray-200">
      <div> <h1 class="text-4xl text-gray-800"> Leads </h1></div>
      <div><a href="{% url 'leads:create' %}" class="text-gray-500 hover:text-blue-700 ">Create new lead</a></div>
          </div>
      </hr>
    <div class="flex flex-wrap -m-4 mt-2" >
        {% for  item in leads %}
              <div class="p-4 lg:w-1/2 md:w-full">
                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                  <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                      <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                      <circle cx="12" cy="7" r="4"></circle>
                    </svg>
                  </div>
                  <div class="flex-grow">
                    <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{item.first_name}} - {{item.last_name}}</h2>
                    <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
                    <a href="{% url 'leads:details' pk=item.id  %}" class="mt-3 text-indigo-500 inline-flex items-center">Learn More
                      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
        {% endfor %}
    </div>
  </div>
</section>
{% endblock %}